<a href="https://colab.research.google.com/github/HiagoCMWesz/programacao_python/blob/main/Trabalho_de_L%C3%B3gica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#APENAS LISTA
import pandas as pd
import io

data = """01 Alice Santos 19 1 Sim Não
02 Bruno Alves 25 4 Não Sim
03 Carla Souza 17 0 Sim Não
04 Daniel Lima 30 7 Sim Sim
05 Elena Silva 21 2 Não Não
06 Fabio Rocha 40 15 Sim Não
07 Gisele Melo 23 3 Sim Sim
08 Hugo Peron 18 0 Não Não
09 Igor Gomes 28 5 Não Sim
10 Julia Costa 22 2 Sim Não
11 Kauê Ramos 20 1 Não Não
12 Liz Duarte 35 10 Sim Sim
13 Marcos Vaz 19 2 Sim Não
14 Nina Sales 24 4 Não Sim
15 Otto Cruz 29 6 Sim Não
16 Paula Dias 17 1 Sim Não
17 Quico Neto 21 0 Não Não
18 Rosa Lima 45 20 Não Sim
19 Saul Reis 26 5 Sim Não
20 Tati Belo 22 3 Não Sim
21 Uriel Luz 18 0 Sim Não
22 Vitor Paz 31 8 Não Sim
23 Wendy Sol 20 1 Sim Não
24 Xandy Farias 27 4 Não Não
25 Yuri Zago 23 2 Sim Sim
26 Zeca Silva 19 1 Não Não
27 Alan Terra 33 9 Sim Sim
28 Bia Nunes 20 2 Não Não
29 Caio Mello 17 0 Não Não
30 Dora Lins 25 3 Sim Sim
31 Enzo Ferraz 18 1 Não Não
32 Fred Góes 42 18 Sim Não
33 Giba Orta 22 2 Não Sim
34 Helô Maia 21 1 Sim Não
35 Isis Vale 24 4 Não Não
36 Juca Terto 30 6 Sim Sim
37 Kelly Pires 19 0 Não Não
38 Léo Fontes 28 5 Sim Não
39 Mara Jobim 20 2 Não Sim
40 Noel Rosa 50 25 Não Não
41 Olga Telles 22 3 Sim Não
42 Pepe Lopez 18 1 Não Não
43 Ruth Lemos 26 4 Sim Sim
44 Sara Otoni 23 2 Não Não
45 Tomé Silva 31 8 Sim Não
46 Una Costa 19 0 Não Sim
47 Valter Zen 28 5 Sim Sim
48 Will Smith 24 3 Não Não
49 Zara Lima 21 1 Sim Não
50 Ari Pires 18 0 Não Não"""

# Nomear as Colunas
columns = ['ID', 'Nome', 'Sobrenome', 'Idade', 'Exp', 'Tecnico', 'Ingles']

# Read the data string into a DataFrame using io.StringIO
df = pd.read_csv(io.StringIO(data), sep=' ', names=columns, encoding='utf-8')

# trocar 'Idade' e 'Exp' para valores numericos
df['Idade'] = pd.to_numeric(df['Idade'])
df['Exp'] = pd.to_numeric(df['Exp'])

In [12]:
# Mostra todo Dataframe (lista)
print("LISTA:")
display(df.set_index('ID'))

Full DataFrame:

      Nome Sobrenome  Idade  Exp Tecnico Ingles
ID
1    Alice    Santos     19    1     Sim    Não
2    Bruno     Alves     25    4     Não    Sim
3    Carla     Souza     17    0     Sim    Não
4   Daniel      Lima     30    7     Sim    Sim
5    Elena     Silva     21    2     Não    Não
6    Fabio     Rocha     40   15     Sim    Não
7   Gisele      Melo     23    3     Sim    Sim
8     Hugo     Peron     18    0     Não    Não
9     Igor     Gomes     28    5     Não    Sim
10   Julia     Costa     22    2     Sim    Não
11    Kauê     Ramos     20    1     Não    Não
12     Liz    Duarte     35   10     Sim    Sim
13  Marcos       Vaz     19    2     Sim    Não
14    Nina     Sales     24    4     Não    Sim
15    Otto      Cruz     29    6     Sim    Não
16   Paula      Dias     17    1     Sim    Não
17   Quico      Neto     21    0     Não    Não
18    Rosa      Lima     45   20     Não    Sim
19    Saul      Reis     26    5     Sim    Não
20    Tati      Belo     22    3     Não    Sim
21   Uriel       Luz     18    0     Sim    Não
22   Vitor       Paz     31    8     Não    Sim
23   Wendy       Sol     20    1     Sim    Não
24   Xandy    Farias     27    4     Não    Não
25    Yuri      Zago     23    2     Sim    Sim
26    Zeca     Silva     19    1     Não    Não
27    Alan     Terra     33    9     Sim    Sim
28     Bia     Nunes     20    2     Não    Não
29    Caio     Mello     17    0     Não    Não
30    Dora      Lins     25    3     Sim    Sim
31    Enzo    Ferraz     18    1     Não    Não
32    Fred      Góes     42   18     Sim    Não
33    Giba      Orta     22    2     Não    Sim
34    Helô      Maia     21    1     Sim    Não
35    Isis      Vale     24    4     Não    Não
36    Juca     Terto     30    6     Sim    Sim
37   Kelly     Pires     19    0     Não    Não
38     Léo    Fontes     28    5     Sim    Não
39    Mara     Jobim     20    2     Não    Sim
40    Noel      Rosa     50   25     Não    Não
41    Olga    Telles     22    3     Sim    Não
42    Pepe     Lopez     18    1     Não    Não
43    Ruth     Lemos     26    4     Sim    Sim
44    Sara     Otoni     23    2     Não    Não
45    Tomé     Silva     31    8     Sim    Não
46     Una     Costa     19    0     Não    Sim
47  Valter       Zen     28    5     Sim    Sim
48    Will     Smith     24    3     Não    Não
49    Zara      Lima     21    1     Sim    Não
50     Ari     Pires     18    0     Não    Não

In [6]:
# Regras para qualificar o candidato
qualified_candidates = df[
    (df['Exp'] >= 2) &
    (df['Tecnico'] == 'Sim') &
    (df['Ingles'] == 'Sim') &
    (df['Idade'] >= 18) &
    (df['Idade'] <= 30)
]

# Mostrar os perfis adequados (ordem por ID)
print("\nPerfis Adequados (seguem todas as regras):")
display(qualified_candidates.set_index('ID'))

Perfis Adequados (seguem todas as regras):

      Nome Sobrenome  Idade  Exp Tecnico Ingles
ID
4   Daniel      Lima     30    7     Sim    Sim
7   Gisele      Melo     23    3     Sim    Sim
25    Yuri      Zago     23    2     Sim    Sim
30    Dora      Lins     25    3     Sim    Sim
36    Juca     Terto     30    6     Sim    Sim
43    Ruth     Lemos     26    4     Sim    Sim
47  Valter       Zen     28    5     Sim    Sim

In [7]:
# DESAFIO 1

qualified_candidates = df[
    (df['Tecnico'] == 'Sim') &
    (df['Idade'] >= 18)
]

# Mostrar os perfis adequados (ordem por ID)
print("\nPerfis Adequados (seguem todas as regras):")
display(qualified_candidates.set_index('ID'))

Perfis Adequados (seguem todas as regras):

      Nome Sobrenome  Idade  Exp Tecnico Ingles
ID
1    Alice    Santos     19    1     Sim    Não
4   Daniel      Lima     30    7     Sim    Sim
6    Fabio     Rocha     40   15     Sim    Não
7   Gisele      Melo     23    3     Sim    Sim
10   Julia     Costa     22    2     Sim    Não
12     Liz    Duarte     35   10     Sim    Sim
13  Marcos       Vaz     19    2     Sim    Não
15    Otto      Cruz     29    6     Sim    Não
19    Saul      Reis     26    5     Sim    Não
21   Uriel       Luz     18    0     Sim    Não
23   Wendy       Sol     20    1     Sim    Não
25    Yuri      Zago     23    2     Sim    Sim
27    Alan     Terra     33    9     Sim    Sim
30    Dora      Lins     25    3     Sim    Sim
32    Fred      Góes     42   18     Sim    Não
34    Helô      Maia     21    1     Sim    Não
36    Juca     Terto     30    6     Sim    Sim
38     Léo    Fontes     28    5     Sim    Não
41    Olga    Telles     22    3     Sim    Não
43    Ruth     Lemos     26    4     Sim    Sim
45    Tomé     Silva     31    8     Sim    Não
47  Valter       Zen     28    5     Sim    Sim
49    Zara      Lima     21    1     Sim    Não

In [8]:
# DESAFIO 2

qualified_candidates = df[
    (df['Exp'] >= 3) &
    (df['Ingles'] == 'Sim')
]

# Mostrar os perfis adequados (ordem por ID)
print("\nPerfis Adequados (seguem todas as regras):")
display(qualified_candidates.set_index('ID'))

Perfis Adequados (seguem todas as regras):

      Nome Sobrenome  Idade  Exp Tecnico Ingles
ID
2    Bruno     Alves     25    4     Não    Sim
4   Daniel      Lima     30    7     Sim    Sim
7   Gisele      Melo     23    3     Sim    Sim
9     Igor     Gomes     28    5     Não    Sim
12     Liz    Duarte     35   10     Sim    Sim
14    Nina     Sales     24    4     Não    Sim
18    Rosa      Lima     45   20     Não    Sim
20    Tati      Belo     22    3     Não    Sim
22   Vitor       Paz     31    8     Não    Sim
27    Alan     Terra     33    9     Sim    Sim
30    Dora      Lins     25    3     Sim    Sim
36    Juca     Terto     30    6     Sim    Sim
43    Ruth     Lemos     26    4     Sim    Sim
47  Valter       Zen     28    5     Sim    Sim

In [10]:
# DESAFIO 3

qualified_candidates = df[
    (df['Exp'] >= 1) | ((df['Tecnico'] == 'Sim') &
    (df['Idade'] >= 24))
]

# Mostrar os perfis adequados (ordem por ID)
print("\nPerfis Adequados (seguem todas as regras):")
display(qualified_candidates.set_index('ID'))

Perfis Adequados (seguem todas as regras):

      Nome Sobrenome  Idade  Exp Tecnico Ingles
ID
1    Alice    Santos     19    1     Sim    Não
2    Bruno     Alves     25    4     Não    Sim
4   Daniel      Lima     30    7     Sim    Sim
5    Elena     Silva     21    2     Não    Não
6    Fabio     Rocha     40   15     Sim    Não
7   Gisele      Melo     23    3     Sim    Sim
9     Igor     Gomes     28    5     Não    Sim
10   Julia     Costa     22    2     Sim    Não
11    Kauê     Ramos     20    1     Não    Não
12     Liz    Duarte     35   10     Sim    Sim
13  Marcos       Vaz     19    2     Sim    Não
14    Nina     Sales     24    4     Não    Sim
15    Otto      Cruz     29    6     Sim    Não
16   Paula      Dias     17    1     Sim    Não
18    Rosa      Lima     45   20     Não    Sim
19    Saul      Reis     26    5     Sim    Não
20    Tati      Belo     22    3     Não    Sim
22   Vitor       Paz     31    8     Não    Sim
23   Wendy       Sol     20    1     Sim    Não
24   Xandy    Farias     27    4     Não    Não
25    Yuri      Zago     23    2     Sim    Sim
26    Zeca     Silva     19    1     Não    Não
27    Alan     Terra     33    9     Sim    Sim
28     Bia     Nunes     20    2     Não    Não
30    Dora      Lins     25    3     Sim    Sim
31    Enzo    Ferraz     18    1     Não    Não
32    Fred      Góes     42   18     Sim    Não
33    Giba      Orta     22    2     Não    Sim
34    Helô      Maia     21    1     Sim    Não
35    Isis      Vale     24    4     Não    Não
36    Juca     Terto     30    6     Sim    Sim
38     Léo    Fontes     28    5     Sim    Não
39    Mara     Jobim     20    2     Não    Sim
40    Noel      Rosa     50   25     Não    Não
41    Olga    Telles     22    3     Sim    Não
42    Pepe     Lopez     18    1     Não    Não
43    Ruth     Lemos     26    4     Sim    Sim
44    Sara     Otoni     23    2     Não    Não
45    Tomé     Silva     31    8     Sim    Não
47  Valter       Zen     28    5     Sim    Sim
48    Will     Smith     24    3     Não    Não
49    Zara      Lima     21    1     Sim    Não

In [18]:
# DESAFIO 4

import numpy as np

# Categorias Novas
df['Categoria'] = np.where(df['Exp'] > 5, 'SÊNIOR', 'JÚNIOR')

# Separar entre Júnior e Sênior
senior_candidates = df[df['Categoria'] == 'SÊNIOR']
junior_candidates = df[df['Categoria'] == 'JÚNIOR']

# Mostrar Sênior
print("\nCandidatos SÊNIOR:")
display(senior_candidates[['ID', 'Nome', 'Sobrenome', 'Exp', 'Tecnico', 'Ingles']].set_index('ID'))

# Mostrar Júnior
print("\nCandidatos JÚNIOR:")
display(junior_candidates[['ID', 'Nome', 'Sobrenome', 'Exp', 'Tecnico', 'Ingles']].set_index('ID'))

Candidatos SÊNIOR:

      Nome Sobrenome  Exp Tecnico Ingles
ID
4   Daniel      Lima    7     Sim    Sim
6    Fabio     Rocha   15     Sim    Não
12     Liz    Duarte   10     Sim    Sim
15    Otto      Cruz    6     Sim    Não
18    Rosa      Lima   20     Não    Sim
22   Vitor       Paz    8     Não    Sim
27    Alan     Terra    9     Sim    Sim
32    Fred      Góes   18     Sim    Não
36    Juca     Terto    6     Sim    Sim
40    Noel      Rosa   25     Não    Não
45    Tomé     Silva    8     Sim    Não

Candidatos JÚNIOR:

      Nome Sobrenome  Exp Tecnico Ingles
ID
1    Alice    Santos    1     Sim    Não
2    Bruno     Alves    4     Não    Sim
3    Carla     Souza    0     Sim    Não
5    Elena     Silva    2     Não    Não
7   Gisele      Melo    3     Sim    Sim
8     Hugo     Peron    0     Não    Não
9     Igor     Gomes    5     Não    Sim
10   Julia     Costa    2     Sim    Não
11    Kauê     Ramos    1     Não    Não
13  Marcos       Vaz    2     Sim    Não
14    Nina     Sales    4     Não    Sim
16   Paula      Dias    1     Sim    Não
17   Quico      Neto    0     Não    Não
19    Saul      Reis    5     Sim    Não
20    Tati      Belo    3     Não    Sim
21   Uriel       Luz    0     Sim    Não
23   Wendy       Sol    1     Sim    Não
24   Xandy    Farias    4     Não    Não
25    Yuri      Zago    2     Sim    Sim
26    Zeca     Silva    1     Não    Não
28     Bia     Nunes    2     Não    Não
29    Caio     Mello    0     Não    Não
30    Dora      Lins    3     Sim    Sim
31    Enzo    Ferraz    1     Não    Não
33    Giba      Orta    2     Não    Sim
34    Helô      Maia    1     Sim    Não
35    Isis      Vale    4     Não    Não
37   Kelly     Pires    0     Não    Não
38     Léo    Fontes    5     Sim    Não
39    Mara     Jobim    2     Não    Sim
41    Olga    Telles    3     Sim    Não
42    Pepe     Lopez    1     Não    Não
43    Ruth     Lemos    4     Sim    Sim
44    Sara     Otoni    2     Não    Não
46     Una     Costa    0     Não    Sim
47  Valter       Zen    5     Sim    Sim
48    Will     Smith    3     Não    Não
49    Zara      Lima    1     Sim    Não
50     Ari     Pires    0     Não    Não